version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install --legacy-peer-deps

  build:
    commands:
      - VITE_API_BASE_URL=https://n2f7znze3m.execute-api.us-east-1.amazonaws.com/dev npm run build

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
