version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install --legacy-peer-deps

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
