version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd backend
      - npm install

  pre_build:
    commands:
      - echo "Running prepare step..."
      - cd backend
      - mkdir -p populate
      - cp src/functions/populate/* populate

  build:
    commands:
      - echo "Building project..."
      - cd backend
      - npm run build
      - echo "Deploying via Serverless..."
      - npx serverless deploy

  post_build:
    commands:
      - echo "Cleaning up..."
      - cd backend
      - rm -rf ./populate

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - 'backend/node_modules/**/*'