version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g serverless
      - npm install --legacy-peer-deps

  build:
    commands:
      - npm run build
      - serverless deploy --stage dev

artifacts:
  files:
    - '**/*'
