const questionBank = [
  {
    topicId: "History",
    question: "Who was the first President of the United States?",
    answers: [
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John Adams",
    ],
    correctAnswer: "George Washington",
  },
  {
    topicId: "History",
    question: "In which year did World War II end?",
    answers: ["1945", "1939", "1918", "1950-April"],
    correctAnswer: "1945",
  },
  {
    topicId: "History",
    question: "What ancient civilization built the pyramids?",
    answers: ["Egyptians", "Romans", "Aztecs", "Greeks"],
    correctAnswer: "Egyptians",
  },
  {
    topicId: "History",
    question:
      "What was the name of the ship that sank in 1912 after hitting an iceberg?",
    answers: ["Titanic", "Lusitania", "Queen Mary", "Endeavour"],
    correctAnswer: "Titanic",
  },
  {
    topicId: "History",
    question: "Who discovered America in 1492?",
    answers: [
      "Christopher Columbus",
      "Ferdinand Magellan",
      "Marco Polo",
      "Leif Erikson",
    ],
    correctAnswer: "Christopher Columbus",
  },
  {
    topicId: "History",
    question: "What wall divided East and West Berlin during the Cold War?",
    answers: ["Berlin Wall", "Great Wall", "Iron Curtain", "Wall of Europe"],
    correctAnswer: "Berlin Wall",
  },
  {
    topicId: "History",
    question: "Which country was responsible for the attack on Pearl Harbor?",
    answers: ["Japan", "Germany", "Italy", "Russia"],
    correctAnswer: "Japan",
  },
  {
    topicId: "History",
    question: "Who was the leader of the Soviet Union during World War II?",
    answers: [
      "Joseph Stalin",
      "Vladimir Lenin",
      "Nikita Khrushchev",
      "Mikhail Gorbachev",
    ],
    correctAnswer: "Joseph Stalin",
  },
  {
    topicId: "History",
    question: "What historical event began on July 28, 1914?",
    answers: [
      "World War I",
      "World War II",
      "The Cold War",
      "The American Revolution",
    ],
    correctAnswer: "World War I",
  },
  {
    topicId: "History",
    question: "Who was the first President of the United States?",
    answers: [
      "George Washington",
      "Thomas Jefferson",
      "Abraham Lincoln",
      "John Adams",
    ],
    correctAnswer: "George Washington",
  },
  {
    topicId: "Geography",
    question: "What is the longest river in the world?",
    answers: [
      "Amazon River",
      "Nile River",
      "Yangtze River",
      "Mississippi River",
    ],
    correctAnswer: "Nile River",
  },
  {
    topicId: "Geography",
    question: "Which country has the largest land area?",
    answers: ["Canada", "Russia", "China", "United States"],
    correctAnswer: "Russia",
  },
  {
    topicId: "Geography",
    question: "Mount Everest lies in which mountain range?",
    answers: ["Andes", "Rockies", "Alps", "Himalayas"],
    correctAnswer: "Himalayas",
  },
  {
    topicId: "Geography",
    question: "Which is the smallest country in the world?",
    answers: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    correctAnswer: "Vatican City",
  },
  {
    topicId: "Geography",
    question: "Which continent has the most countries?",
    answers: ["Asia", "Africa", "Europe", "South America"],
    correctAnswer: "Africa",
  },
  {
    topicId: "Geography",
    question: "Which ocean is the deepest?",
    answers: ["Atlantic", "Indian", "Arctic", "Pacific"],
    correctAnswer: "Pacific",
  },
  {
    topicId: "Geography",
    question: "What desert is the largest in the world?",
    answers: ["Gobi", "Kalahari", "Sahara", "Antarctic Desert"],
    correctAnswer: "Antarctic Desert",
  },
  {
    topicId: "Geography",
    question: "Which U.S. state is the largest by area?",
    answers: ["Texas", "California", "Alaska", "Montana"],
    correctAnswer: "Alaska",
  },
  {
    topicId: "Geography",
    question: "Which country has the most time zones?",
    answers: ["USA", "Russia", "France", "China"],
    correctAnswer: "France",
  },
  {
    topicId: "Geography",
    question: "What is the capital of Canada?",
    answers: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    correctAnswer: "Ottawa",
  },
  {
    topicId: "Sports",
    question: "Which country won the FIFA World Cup in 2022?",
    answers: ["Argentina", "France", "Germany", "Brazil"],
    correctAnswer: "Argentina",
  },
  {
    topicId: "Sports",
    question: "Who holds the record for most Grand Slam tennis titles (men)?",
    answers: [
      "Novak Djokovic",
      "Roger Federer",
      "Rafael Nadal",
      "Pete Sampras",
    ],
    correctAnswer: "Novak Djokovic",
  },
  {
    topicId: "Sports",
    question: "Which NFL team has won the most Super Bowls?",
    answers: [
      "New England Patriots",
      "Pittsburgh Steelers",
      "Dallas Cowboys",
      "San Francisco 49ers",
    ],
    correctAnswer: "New England Patriots",
  },
  {
    topicId: "Sports",
    question: "Who is known as 'The King of Football'?",
    answers: ["Maradona", "Pelé", "Cristiano Ronaldo", "Zidane"],
    correctAnswer: "Pelé",
  },
  {
    topicId: "Sports",
    question: "What sport does Serena Williams play?",
    answers: ["Tennis", "Golf", "Soccer", "Badminton"],
    correctAnswer: "Tennis",
  },
  {
    topicId: "Sports",
    question: "In which year were the first modern Olympic Games held?",
    answers: ["1896", "1900", "1888", "1912"],
    correctAnswer: "1896",
  },
  {
    topicId: "Sports",
    question: "How many players are there in a baseball team?",
    answers: ["9", "11", "7", "10"],
    correctAnswer: "9",
  },
  {
    topicId: "Sports",
    question: "Which country has won the most Olympic gold medals in total?",
    answers: ["USA", "Russia", "China", "Germany"],
    correctAnswer: "USA",
  },
  {
    topicId: "Sports",
    question: "Which sport is known as the 'king of sports'?",
    answers: ["Soccer", "Cricket", "Basketball", "Baseball"],
    correctAnswer: "Soccer",
  },
  {
    topicId: "Sports",
    question: "Which country hosts the Tour de France cycling race?",
    answers: ["France", "Spain", "Italy", "Switzerland"],
    correctAnswer: "France",
  },
  {
    topicId: "Sports",
    question: "What is the maximum score in a single frame of bowling?",
    answers: ["30", "10", "20", "15"],
    correctAnswer: "30",
  },
  {
    topicId: "Sports",
    question: "How many rings are there on the Olympic flag?",
    answers: ["5", "4", "6", "7"],
    correctAnswer: "5",
  },
  {
    topicId: "Mathematics",
    question: "What is the value of π (pi) approximately?",
    answers: ["3.14", "2.71", "1.61", "1.41"],
    correctAnswer: "3.14",
  },
  {
    topicId: "Mathematics",
    question: "What is the square root of 144?",
    answers: ["10", "11", "12", "13"],
    correctAnswer: "12",
  },
  {
    topicId: "Mathematics",
    question: "What is 7 x 8?",
    answers: ["54", "56", "58", "60"],
    correctAnswer: "56",
  },
  {
    topicId: "Mathematics",
    question: "What is the area of a circle with radius 3?",
    answers: ["18π", "6π", "9π", "12π"],
    correctAnswer: "9π",
  },
  {
    topicId: "Mathematics",
    question: "What is the value of 2^5?",
    answers: ["32", "64", "16", "8"],
    correctAnswer: "32",
  },
  {
    topicId: "Mathematics",
    question: "What is the derivative of x²?",
    answers: ["x", "2x", "x²", "2"],
    correctAnswer: "2x",
  },
  {
    topicId: "Mathematics",
    question: "What is 15% of 200?",
    answers: ["25", "30", "35", "40"],
    correctAnswer: "30",
  },
  {
    topicId: "Mathematics",
    question: "What is the next prime number after 7?",
    answers: ["9", "10", "11", "13"],
    correctAnswer: "11",
  },
  {
    topicId: "Mathematics",
    question: "Solve: 3x + 5 = 14",
    answers: ["x = 2", "x = 3", "x = 4", "x = 5"],
    correctAnswer: "x = 3",
  },
  {
    topicId: "Mathematics",
    question: "What is the factorial of 5?",
    answers: ["60", "100", "120", "150"],
    correctAnswer: "120",
  },
  {
    topicId: "Mathematics",
    question: "What is the mean of 4, 8, 12?",
    answers: ["6", "8", "10", "12"],
    correctAnswer: "8",
  },
  {
    topicId: "Mathematics",
    question: "What is the smallest prime number?",
    answers: ["0", "1", "2", "3"],
    correctAnswer: "2",
  },
  {
    topicId: "Mathematics",
    question: "If x + 3 = 7, what is x?",
    answers: ["3", "4", "5", "6"],
    correctAnswer: "4",
  },
  {
    topicId: "Mathematics",
    question: "What is the perimeter of a square with side 5?",
    answers: ["10", "15", "20", "25"],
    correctAnswer: "20",
  },
  {
    topicId: "Mathematics",
    question: "How many degrees in a right angle?",
    answers: ["45", "60", "90", "120"],
    correctAnswer: "90",
  },
  {
    topicId: "Mathematics",
    question: "What is the cube root of 27?",
    answers: ["2", "3", "4", "5"],
    correctAnswer: "3",
  },
  {
    topicId: "Mathematics",
    question: "What is 100 divided by 4?",
    answers: ["20", "25", "30", "40"],
    correctAnswer: "25",
  },
  {
    topicId: "Mathematics",
    question: "What is 10 squared?",
    answers: ["10", "100", "1000", "20"],
    correctAnswer: "100",
  },
  {
    topicId: "Mathematics",
    question: "How many sides does a hexagon have?",
    answers: ["5", "6", "7", "8"],
    correctAnswer: "6",
  },
  {
    topicId: "Mathematics",
    question: "What is the greatest common divisor of 12 and 18?",
    answers: ["2", "3", "6", "9"],
    correctAnswer: "6",
  },
  {
    topicId: "Mathematics",
    question: "If a triangle has sides 3, 4, and 5, it is a:",
    answers: ["Scalene", "Isosceles", "Equilateral", "Right triangle"],
    correctAnswer: "Right triangle",
  },
  {
    topicId: "Mathematics",
    question: "What is 9 × 9?",
    answers: ["81", "72", "99", "90"],
    correctAnswer: "81",
  },
  {
    topicId: "Mathematics",
    question: "What is 3/4 as a decimal?",
    answers: ["0.5", "0.6", "0.75", "0.8"],
    correctAnswer: "0.75",
  },
  {
    topicId: "Mathematics",
    question: "What comes next in the sequence: 2, 4, 8, 16, ___?",
    answers: ["20", "24", "32", "36"],
    correctAnswer: "32",
  },
  {
    topicId: "Mathematics",
    question: "What is the median of 3, 7, 9?",
    answers: ["3", "7", "9", "6"],
    correctAnswer: "7",
  },
  {
    topicId: "Mathematics",
    question: "Solve for x: 2x = 10",
    answers: ["2", "4", "5", "6"],
    correctAnswer: "5",
  },
  {
    topicId: "Mathematics",
    question: "What is the value of sin(90°)?",
    answers: ["0", "0.5", "1", "Undefined"],
    correctAnswer: "1",
  },
  {
    topicId: "Mathematics",
    question: "What is 3² + 4²?",
    answers: ["25", "16", "12", "7"],
    correctAnswer: "25",
  },
  {
    topicId: "Mathematics",
    question: "What is the smallest even number?",
    answers: ["0", "1", "2", "3"],
    correctAnswer: "0",
  },
  {
    topicId: "Mathematics",
    question: "What is the mode of 2, 4, 4, 6?",
    answers: ["2", "4", "6", "No mode"],
    correctAnswer: "4",
  },
  {
    topicId: "Mathematics",
    question: "What is 1/2 of 100?",
    answers: ["25", "50", "75", "100"],
    correctAnswer: "50",
  },
  {
    topicId: "Mathematics",
    question: "Which of these is a multiple of both 3 and 5?",
    answers: ["10", "15", "20", "25"],
    correctAnswer: "15",
  },
  {
    topicId: "Mathematics",
    question: "How many zeros in one million?",
    answers: ["4", "5", "6", "7"],
    correctAnswer: "6",
  },
  {
    topicId: "Mathematics",
    question: "What is 8 ÷ 2(2+2)?",
    answers: ["1", "16", "8", "4"],
    correctAnswer: "1",
  },
  {
    topicId: "Mathematics",
    question: "What is the probability of flipping heads on a fair coin?",
    answers: ["0.25", "0.5", "0.75", "1"],
    correctAnswer: "0.5",
  },
  {
    topicId: "Mathematics",
    question: "What is 2 + 2 × 2?",
    answers: ["6", "8", "4", "10"],
    correctAnswer: "6",
  },
  {
    topicId: "Mathematics",
    question: "What is the formula for area of a rectangle?",
    answers: ["l + w", "l × w", "2l + 2w", "πr²"],
    correctAnswer: "l × w",
  },
  {
    topicId: "Mathematics",
    question: "What is the slope of a horizontal line?",
    answers: ["0", "1", "∞", "Undefined"],
    correctAnswer: "0",
  },
  {
    topicId: "Mathematics",
    question: "What is the sum of interior angles in a triangle?",
    answers: ["90°", "180°", "270°", "360°"],
    correctAnswer: "180°",
  },
  {
    topicId: "Mathematics",
    question: "What is the logarithm of 100 base 10?",
    answers: ["1", "2", "10", "100"],
    correctAnswer: "2",
  },
  {
    topicId: "Mathematics",
    question: "Which of the following is irrational?",
    answers: ["1.5", "√2", "2", "0.25"],
    correctAnswer: "√2",
  },
  {
    topicId: "Mathematics",
    question: "If x = 3, what is 2x + 4?",
    answers: ["6", "8", "10", "12"],
    correctAnswer: "10",
  },
  {
    topicId: "Mathematics",
    question: "Which shape has 4 sides?",
    answers: ["Triangle", "Square", "Pentagon", "Circle"],
    correctAnswer: "Square",
  },
  {
    topicId: "Mathematics",
    question: "What is the additive identity?",
    answers: ["0", "1", "∞", "-1"],
    correctAnswer: "0",
  },
  {
    topicId: "Mathematics",
    question: "What is the multiplicative identity?",
    answers: ["0", "1", "10", "100"],
    correctAnswer: "1",
  },
  {
    topicId: "Mathematics",
    question: "What is 6% of 50?",
    answers: ["3", "6", "12", "15"],
    correctAnswer: "3",
  },
  {
    topicId: "Mathematics",
    question: "What is the square root of 81?",
    answers: ["7", "8", "9", "10"],
    correctAnswer: "9",
  },
  {
    topicId: "Mathematics",
    question: "How many sides does a decagon have?",
    answers: ["8", "9", "10", "12"],
    correctAnswer: "10",
  },
  {
    topicId: "AWS",
    question: "What does EC2 stand for?",
    answers: [
      "Elastic Compute Cloud",
      "Elastic Cloud Compute",
      "External Compute Cloud",
      "Elastic Container Cloud",
    ],
    correctAnswer: "Elastic Compute Cloud",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is used to store objects?",
    answers: ["Amazon S3", "Amazon EC2", "Amazon EBS", "Amazon RDS"],
    correctAnswer: "Amazon S3",
  },
  {
    topicId: "AWS",
    question: "Which database is a managed NoSQL service in AWS?",
    answers: [
      "Amazon Aurora",
      "Amazon RDS",
      "Amazon Redshift",
      "Amazon DynamoDB",
    ],
    correctAnswer: "Amazon DynamoDB",
  },
  {
    topicId: "AWS",
    question: "What service provides serverless compute in AWS?",
    answers: ["EC2", "ECS", "Lambda", "Elastic Beanstalk"],
    correctAnswer: "Lambda",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is used for DNS?",
    answers: [
      "Amazon VPC",
      "Amazon Route 53",
      "Amazon CloudFront",
      "Amazon EC2",
    ],
    correctAnswer: "Amazon Route 53",
  },
  {
    topicId: "AWS",
    question: "What is the main benefit of using AWS Availability Zones?",
    answers: [
      "Increased storage capacity",
      "Improved compute performance",
      "Fault isolation and redundancy",
      "Reduced billing cost",
    ],
    correctAnswer: "Fault isolation and redundancy",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is used for content delivery?",
    answers: [
      "Amazon Route 53",
      "Amazon CloudFront",
      "Amazon VPC",
      "Amazon IAM",
    ],
    correctAnswer: "Amazon CloudFront",
  },
  {
    topicId: "AWS",
    question: "What is the AWS service for creating isolated cloud networks?",
    answers: ["Amazon CloudFront", "Amazon VPC", "Amazon S3", "Amazon ECS"],
    correctAnswer: "Amazon VPC",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is a relational database?",
    answers: [
      "Amazon S3",
      "Amazon DynamoDB",
      "Amazon RDS",
      "Amazon CloudWatch",
    ],
    correctAnswer: "Amazon RDS",
  },
  {
    topicId: "AWS",
    question: "What is IAM used for in AWS?",
    answers: [
      "Launching instances",
      "Data analytics",
      "Managing permissions and users",
      "Monitoring applications",
    ],
    correctAnswer: "Managing permissions and users",
  },
  {
    topicId: "AWS",
    question: "Which AWS service helps you monitor resources and logs?",
    answers: ["Amazon CloudWatch", "Amazon Route 53", "AWS Glue", "Amazon VPC"],
    correctAnswer: "Amazon CloudWatch",
  },
  {
    topicId: "AWS",
    question: "What is the purpose of AWS Auto Scaling?",
    answers: [
      "Scaling database size",
      "Scaling instances based on demand",
      "Scaling storage volume",
      "Scaling billing plans",
    ],
    correctAnswer: "Scaling instances based on demand",
  },
  {
    topicId: "AWS",
    question: "What is the primary use of AWS CloudFormation?",
    answers: [
      "Application monitoring",
      "Infrastructure as Code",
      "Load balancing",
      "Object storage",
    ],
    correctAnswer: "Infrastructure as Code",
  },
  {
    topicId: "AWS",
    question: "Which service provides managed Kubernetes?",
    answers: ["ECS", "EKS", "Lambda", "CodeDeploy"],
    correctAnswer: "EKS",
  },
  {
    topicId: "AWS",
    question: "What does AWS Shield protect against?",
    answers: ["Malware", "Unauthorized access", "DDoS attacks", "Data loss"],
    correctAnswer: "DDoS attacks",
  },
  {
    topicId: "AWS",
    question: "Which AWS service manages secrets securely?",
    answers: ["AWS IAM", "AWS Secrets Manager", "AWS SSM", "Amazon RDS"],
    correctAnswer: "AWS Secrets Manager",
  },
  {
    topicId: "AWS",
    question: "What is the maximum size of a single S3 object?",
    answers: ["1 TB", "5 GB", "10 TB", "50 TB"],
    correctAnswer: "5 TB",
  },
  {
    topicId: "AWS",
    question: "What does AWS Elastic Beanstalk do?",
    answers: [
      "Provides DDoS protection",
      "Manages cloud infrastructure as code",
      "Deploys and manages web applications",
      "Monitors cloud resources",
    ],
    correctAnswer: "Deploys and manages web applications",
  },
  {
    topicId: "AWS",
    question: "Which service is used for real-time data streaming?",
    answers: ["Amazon Kinesis", "AWS Glue", "Amazon SQS", "Amazon SNS"],
    correctAnswer: "Amazon Kinesis",
  },
  {
    topicId: "AWS",
    question: "Which service is ideal for queuing messages?",
    answers: ["Amazon SNS", "Amazon MQ", "Amazon SQS", "Amazon EventBridge"],
    correctAnswer: "Amazon SQS",
  },
  {
    topicId: "AWS",
    question: "What service does AWS provide for sending notifications?",
    answers: ["Amazon SES", "Amazon SNS", "Amazon SQS", "Amazon Kinesis"],
    correctAnswer: "Amazon SNS",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is a data warehousing solution?",
    answers: [
      "Amazon RDS",
      "Amazon DynamoDB",
      "Amazon Redshift",
      "Amazon Athena",
    ],
    correctAnswer: "Amazon Redshift",
  },
  {
    topicId: "AWS",
    question: "What is Amazon Athena used for?",
    answers: [
      "Running SQL on S3 data",
      "Encrypting data",
      "Monitoring applications",
      "Creating cloud networks",
    ],
    correctAnswer: "Running SQL on S3 data",
  },
  {
    topicId: "AWS",
    question: "What does AWS CloudTrail do?",
    answers: [
      "Manages compute services",
      "Audits and logs API activity",
      "Scales applications",
      "Stores data",
    ],
    correctAnswer: "Audits and logs API activity",
  },
  {
    topicId: "AWS",
    question: "What AWS service is best for hosting static websites?",
    answers: ["Amazon EC2", "Amazon S3", "Amazon RDS", "Amazon VPC"],
    correctAnswer: "Amazon S3",
  },
  {
    topicId: "AWS",
    question: "Which service is a fully managed container service?",
    answers: ["Amazon EKS", "Amazon ECS", "Amazon EC2", "Lambda"],
    correctAnswer: "Amazon ECS",
  },
  {
    topicId: "AWS",
    question: "Which service is best for CI/CD automation?",
    answers: [
      "AWS CodePipeline",
      "AWS Auto Scaling",
      "Amazon EC2",
      "Amazon SNS",
    ],
    correctAnswer: "AWS CodePipeline",
  },
  {
    topicId: "AWS",
    question:
      "Which service enables you to run containers without managing servers?",
    answers: ["ECS with Fargate", "EC2", "EKS", "CodeBuild"],
    correctAnswer: "ECS with Fargate",
  },
  {
    topicId: "AWS",
    question: "Which tool visualizes AWS resource relationships?",
    answers: ["AWS Explorer", "AWS Config", "AWS CloudTrail", "AWS X-Ray"],
    correctAnswer: "AWS Config",
  },
  {
    topicId: "AWS",
    question: "Which AWS service is designed for email sending?",
    answers: ["Amazon SNS", "Amazon SES", "Amazon SQS", "Amazon Kinesis"],
    correctAnswer: "Amazon SES",
  },
  {
    topicId: "AWS",
    question: "Which AWS service provides machine learning models quickly?",
    answers: [
      "Amazon Lex",
      "Amazon SageMaker",
      "Amazon Rekognition",
      "Amazon Comprehend",
    ],
    correctAnswer: "Amazon SageMaker",
  },
  {
    topicId: "AWS",
    question: "Which service encrypts and manages encryption keys?",
    answers: ["AWS IAM", "AWS Shield", "AWS KMS", "AWS Secrets Manager"],
    correctAnswer: "AWS KMS",
  },
  {
    topicId: "AWS",
    question: "Which service enables hybrid cloud storage?",
    answers: ["AWS Storage Gateway", "Amazon EBS", "Amazon S3", "Amazon FSx"],
    correctAnswer: "AWS Storage Gateway",
  },
  {
    topicId: "AWS",
    question: "Which AWS service can host a Docker container directly?",
    answers: ["Amazon ECS", "Amazon S3", "Amazon RDS", "Amazon VPC"],
    correctAnswer: "Amazon ECS",
  },
  {
    topicId: "AWS",
    question: "Which storage type is ideal for frequent access?",
    answers: ["S3 Glacier", "S3 One Zone-IA", "S3 Standard", "EBS Snapshot"],
    correctAnswer: "S3 Standard",
  },
  {
    topicId: "AWS",
    question: "Which service monitors Lambda performance?",
    answers: ["CloudTrail", "CloudWatch", "IAM", "Kinesis"],
    correctAnswer: "CloudWatch",
  },
  {
    topicId: "AWS",
    question: "Which service helps you budget and forecast AWS costs?",
    answers: [
      "AWS Cost Explorer",
      "AWS Inspector",
      "AWS CloudWatch",
      "AWS KMS",
    ],
    correctAnswer: "AWS Cost Explorer",
  },
  {
    topicId: "AWS",
    question: "What is the role of AWS Organizations?",
    answers: [
      "Container orchestration",
      "Creating multiple users",
      "Managing multiple AWS accounts",
      "Monitoring logs",
    ],
    correctAnswer: "Managing multiple AWS accounts",
  },
  {
    topicId: "AWS",
    question: "Which service can migrate on-prem data to AWS?",
    answers: [
      "AWS Migration Hub",
      "AWS DMS",
      "AWS Snowball",
      "All of the above",
    ],
    correctAnswer: "All of the above",
  },
  {
    topicId: "AWS",
    question: "What is a key pair in AWS?",
    answers: [
      "A set of user credentials",
      "A way to encrypt S3 buckets",
      "SSH credentials for EC2 access",
      "Two IAM users linked together",
    ],
    correctAnswer: "SSH credentials for EC2 access",
  },
  {
    topicId: "AWS",
    question: "Which service allows you to schedule jobs?",
    answers: ["AWS Batch", "AWS Glue", "AWS Lambda", "Amazon EventBridge"],
    correctAnswer: "Amazon EventBridge",
  },
  {
    topicId: "AWS",
    question: "Which tool provides security findings and alerts?",
    answers: ["AWS Inspector", "AWS GuardDuty", "AWS KMS", "CloudTrail"],
    correctAnswer: "AWS GuardDuty",
  },
  {
    topicId: "AWS",
    question: "Which service provides threat detection?",
    answers: ["AWS Inspector", "Amazon Macie", "AWS GuardDuty", "AWS IAM"],
    correctAnswer: "AWS GuardDuty",
  },
  {
    topicId: "AWS",
    question: "What is the default limit of IAM users per account?",
    answers: ["50", "100", "5000", "Unlimited"],
    correctAnswer: "5000",
  },
  {
    topicId: "AWS",
    question: "Which AWS feature restricts access based on IP?",
    answers: ["IAM Policies", "Security Groups", "NACLs", "All of the above"],
    correctAnswer: "All of the above",
  },
  {
    topicId: "AWS",
    question: "Which AWS service provides step-by-step workflows?",
    answers: ["Amazon Step Functions", "AWS Glue", "Amazon SWF", "AWS Lambda"],
    correctAnswer: "Amazon Step Functions",
  },
  {
    topicId: "AWS",
    question: "Which AWS service offers object lifecycle management?",
    answers: ["Amazon S3", "Amazon RDS", "Amazon EBS", "Amazon VPC"],
    correctAnswer: "Amazon S3",
  },
  {
    topicId: "AWS",
    question: "Which AWS service can host APIs?",
    answers: ["Amazon API Gateway", "Amazon Lambda", "Amazon EC2", "Amazon S3"],
    correctAnswer: "Amazon API Gateway",
  },
  {
    topicId: "Programming",
    question: "What does HTML stand for?",
    answers: [
      "Hyperlinks and Text Markup Language",
      "Hyper Text Markup Language",
      "Home Tool Markup Language",
      "Hyper Transfer Markup Language",
    ],
    correctAnswer: "Hyper Text Markup Language",
  },
  {
    topicId: "Programming",
    question: "Which language is used for styling web pages?",
    answers: ["HTML", "JQuery", "CSS", "XML"],
    correctAnswer: "CSS",
  },
  {
    topicId: "Programming",
    question: "Inside which HTML element do we put the JavaScript?",
    answers: ["<js>", "<script>", "<javascript>", "<scripting>"],
    correctAnswer: "<script>",
  },
  {
    topicId: "Programming",
    question: "What is the correct syntax for referring to an external script?",
    answers: [
      "<script src='xxx.js'>",
      "<script name='xxx.js'>",
      "<script href='xxx.js'>",
      "<script link='xxx.js'>",
    ],
    correctAnswer: "<script src='xxx.js'>",
  },
  {
    topicId: "Programming",
    question: "Which of the following is a JavaScript data type?",
    answers: ["Number", "Float", "Double", "Character"],
    correctAnswer: "Number",
  },
  {
    topicId: "Programming",
    question: "Which operator is used to assign a value to a variable?",
    answers: ["-", "*", "=", "=="],
    correctAnswer: "=",
  },
  {
    topicId: "Programming",
    question: "What does CSS stand for?",
    answers: [
      "Creative Style Sheets",
      "Cascading Style Sheets",
      "Computer Style Sheets",
      "Colorful Style Sheets",
    ],
    correctAnswer: "Cascading Style Sheets",
  },
  {
    topicId: "Programming",
    question: "Which company developed JavaScript?",
    answers: ["Microsoft", "Netscape", "Google", "Oracle"],
    correctAnswer: "Netscape",
  },
  {
    topicId: "Programming",
    question: "Which method converts JSON to a JavaScript object?",
    answers: [
      "JSON.parse()",
      "JSON.stringify()",
      "JSON.convert()",
      "JSON.toObject()",
    ],
    correctAnswer: "JSON.parse()",
  },
  {
    topicId: "Programming",
    question: "Which one is a backend programming language?",
    answers: ["HTML", "CSS", "Node.js", "React"],
    correctAnswer: "Node.js",
  },

  // 40 more questions below...

  {
    topicId: "Programming",
    question: "What does the '===' operator mean in JavaScript?",
    answers: [
      "Assignment",
      "Equality with type conversion",
      "Strict equality",
      "None of the above",
    ],
    correctAnswer: "Strict equality",
  },
  {
    topicId: "Programming",
    question: "Which language runs in a web browser?",
    answers: ["Java", "C", "Python", "JavaScript"],
    correctAnswer: "JavaScript",
  },
  {
    topicId: "Programming",
    question: "What is the result of 3 + '3' in JavaScript?",
    answers: ["6", "33", "NaN", "Error"],
    correctAnswer: "33",
  },
  {
    topicId: "Programming",
    question: "Which keyword is used to create a constant in JavaScript?",
    answers: ["const", "let", "var", "constant"],
    correctAnswer: "const",
  },
  {
    topicId: "Programming",
    question: "Which function is used to print to the console in JavaScript?",
    answers: ["print()", "log()", "console()", "console.log()"],
    correctAnswer: "console.log()",
  },
  {
    topicId: "Programming",
    question: "Which symbol is used for comments in JavaScript?",
    answers: ["<!-- -->", "//", "**", "##"],
    correctAnswer: "//",
  },
  {
    topicId: "Programming",
    question: "What is a closure in JavaScript?",
    answers: [
      "An object",
      "A function having access to the parent scope",
      "A variable inside a loop",
      "None of the above",
    ],
    correctAnswer: "A function having access to the parent scope",
  },
  {
    topicId: "Programming",
    question: "What is the default port for HTTP?",
    answers: ["80", "443", "21", "8080"],
    correctAnswer: "80",
  },
  {
    topicId: "Programming",
    question: "Which of these is a loop structure in JavaScript?",
    answers: ["repeat", "foreach", "do...while", "loop"],
    correctAnswer: "do...while",
  },
  {
    topicId: "Programming",
    question: "Which keyword is used for asynchronous functions?",
    answers: ["async", "await", "promise", "yield"],
    correctAnswer: "async",
  },

  // 30 more abbreviated for brevity, let me know if you want full code
  {
    topicId: "Programming",
    question: "What is Git used for?",
    answers: [
      "Hosting websites",
      "Running Java programs",
      "Version control",
      "Compiling code",
    ],
    correctAnswer: "Version control",
  },
  {
    topicId: "Programming",
    question: "Which tool is commonly used for frontend build processes?",
    answers: ["Webpack", "Jenkins", "Docker", "Kubernetes"],
    correctAnswer: "Webpack",
  },
  {
    topicId: "Programming",
    question: "What is the purpose of a database index?",
    answers: [
      "To store large files",
      "To enforce constraints",
      "To speed up queries",
      "To increase storage",
    ],
    correctAnswer: "To speed up queries",
  },
  {
    topicId: "Programming",
    question: "Which of these is a NoSQL database?",
    answers: ["MySQL", "PostgreSQL", "MongoDB", "SQLite"],
    correctAnswer: "MongoDB",
  },
  {
    topicId: "Programming",
    question: "What is recursion?",
    answers: [
      "A loop",
      "A function calling itself",
      "A conditional block",
      "An API call",
    ],
    correctAnswer: "A function calling itself",
  },
  [
    {
      topicId: "Entertainment",
      question: "Who directed the movie 'Inception'?",
      answers: [
        "Christopher Nolan",
        "Steven Spielberg",
        "James Cameron",
        "Martin Scorsese",
      ],
      correctAnswer: "Christopher Nolan",
    },
    {
      topicId: "Entertainment",
      question: "Which TV show features the character Sheldon Cooper?",
      answers: [
        "The Big Bang Theory",
        "Friends",
        "Brooklyn Nine-Nine",
        "Modern Family",
      ],
      correctAnswer: "The Big Bang Theory",
    },
    {
      topicId: "Entertainment",
      question: "Which artist sang 'Blinding Lights'?",
      answers: ["The Weeknd", "Drake", "Post Malone", "Bruno Mars"],
      correctAnswer: "The Weeknd",
    },
    {
      topicId: "Entertainment",
      question: "Which movie won Best Picture at the Oscars in 2020?",
      answers: ["Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"],
      correctAnswer: "Parasite",
    },
    {
      topicId: "Entertainment",
      question: "Which streaming service produced 'Stranger Things'?",
      answers: ["Netflix", "HBO Max", "Disney+", "Amazon Prime Video"],
      correctAnswer: "Netflix",
    },
    {
      topicId: "Entertainment",
      question: "What is the name of Harry Potter’s owl?",
      answers: ["Hedwig", "Errol", "Crookshanks", "Scabbers"],
      correctAnswer: "Hedwig",
    },
    {
      topicId: "Entertainment",
      question: "Which movie features a talking snowman named Olaf?",
      answers: ["Frozen", "Moana", "Tangled", "Encanto"],
      correctAnswer: "Frozen",
    },
    {
      topicId: "Entertainment",
      question: "Who played the character of Iron Man in the Marvel movies?",
      answers: [
        "Robert Downey Jr.",
        "Chris Evans",
        "Chris Hemsworth",
        "Mark Ruffalo",
      ],
      correctAnswer: "Robert Downey Jr.",
    },
    {
      topicId: "Entertainment",
      question: "Which band released the album 'Abbey Road'?",
      answers: ["The Beatles", "The Rolling Stones", "Pink Floyd", "Queen"],
      correctAnswer: "The Beatles",
    },
    {
      topicId: "Entertainment",
      question: "What is the name of the fictional country in 'Black Panther'?",
      answers: ["Wakanda", "Narnia", "Zamunda", "Elbonia"],
      correctAnswer: "Wakanda",
    },
    {
      topicId: "Entertainment",
      question: "Who is the host of 'The Tonight Show' as of 2024?",
      answers: [
        "Jimmy Fallon",
        "Stephen Colbert",
        "James Corden",
        "Trevor Noah",
      ],
      correctAnswer: "Jimmy Fallon",
    },
    {
      topicId: "Entertainment",
      question: "Which video game features the character 'Link'?",
      answers: ["The Legend of Zelda", "Final Fantasy", "Skyrim", "Elden Ring"],
      correctAnswer: "The Legend of Zelda",
    },
    {
      topicId: "Entertainment",
      question: "Who voices Gru in the 'Despicable Me' franchise?",
      answers: ["Steve Carell", "Will Ferrell", "Jim Carrey", "Ben Stiller"],
      correctAnswer: "Steve Carell",
    },
    {
      topicId: "Entertainment",
      question:
        "Which reality show is known for the catchphrase 'You're fired'?",
      answers: ["The Apprentice", "Shark Tank", "Survivor", "Big Brother"],
      correctAnswer: "The Apprentice",
    },
    {
      topicId: "Entertainment",
      question:
        "In which movie does Tom Hanks talk to a volleyball named Wilson?",
      answers: [
        "Cast Away",
        "Forrest Gump",
        "Saving Private Ryan",
        "Captain Phillips",
      ],
      correctAnswer: "Cast Away",
    },
    {
      topicId: "Entertainment",
      question: "Which Disney movie features the song 'Circle of Life'?",
      answers: ["The Lion King", "Aladdin", "Tarzan", "Hercules"],
      correctAnswer: "The Lion King",
    },
    {
      topicId: "Entertainment",
      question: "What instrument does Lizzo famously play?",
      answers: ["Flute", "Piano", "Guitar", "Saxophone"],
      correctAnswer: "Flute",
    },
    {
      topicId: "Entertainment",
      question: "Which actor played the Joker in 'The Dark Knight'?",
      answers: [
        "Heath Ledger",
        "Joaquin Phoenix",
        "Jared Leto",
        "Jack Nicholson",
      ],
      correctAnswer: "Heath Ledger",
    },
    {
      topicId: "Entertainment",
      question: "Which show is set in the fictional town of Hawkins, Indiana?",
      answers: [
        "Stranger Things",
        "Riverdale",
        "The Umbrella Academy",
        "The X-Files",
      ],
      correctAnswer: "Stranger Things",
    },
    {
      topicId: "Entertainment",
      question: "Which pop star starred in the movie 'A Star Is Born'?",
      answers: ["Lady Gaga", "Taylor Swift", "Ariana Grande", "Dua Lipa"],
      correctAnswer: "Lady Gaga",
    },
    [
      {
        topicId: "Puzzles",
        question:
          "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
        answers: ["Echo", "Shadow", "Ghost", "Whistle"],
        correctAnswer: "Echo",
      },
      {
        topicId: "Puzzles",
        question:
          "What comes once in a minute, twice in a moment, but never in a thousand years?",
        answers: ["The letter M", "Time", "Blink", "Second"],
        correctAnswer: "The letter M",
      },
      {
        topicId: "Puzzles",
        question:
          "I’m tall when I’m young, and I’m short when I’m old. What am I?",
        answers: ["Candle", "Pencil", "Tree", "Shadow"],
        correctAnswer: "Candle",
      },
      {
        topicId: "Puzzles",
        question: "What can fill a room but takes up no space?",
        answers: ["Light", "Air", "Sound", "Darkness"],
        correctAnswer: "Light",
      },
      {
        topicId: "Puzzles",
        question: "What has keys but can’t open locks?",
        answers: ["Piano", "Keyboard", "Map", "Locksmith"],
        correctAnswer: "Piano",
      },
      {
        topicId: "Puzzles",
        question:
          "The more you take, the more you leave behind. What are they?",
        answers: ["Footsteps", "Memories", "Photos", "Words"],
        correctAnswer: "Footsteps",
      },
      {
        topicId: "Puzzles",
        question: "What gets wetter as it dries?",
        answers: ["Towel", "Sponge", "Raincoat", "Windshield"],
        correctAnswer: "Towel",
      },
      {
        topicId: "Puzzles",
        question: "I have branches, but no fruit, trunk, or leaves. What am I?",
        answers: ["Bank", "Tree", "River", "Family"],
        correctAnswer: "Bank",
      },
      {
        topicId: "Puzzles",
        question:
          "What can travel around the world while staying in the same corner?",
        answers: ["Stamp", "Satellite", "Compass", "Sunlight"],
        correctAnswer: "Stamp",
      },
      {
        topicId: "Puzzles",
        question: "What has a head, a tail, but no body?",
        answers: ["Coin", "Snake", "Comet", "Hammer"],
        correctAnswer: "Coin",
      },
      {
        topicId: "Puzzles",
        question: "What has many teeth but can’t bite?",
        answers: ["Comb", "Zipper", "Saw", "Gears"],
        correctAnswer: "Comb",
      },
      {
        topicId: "Puzzles",
        question: "What comes down but never goes up?",
        answers: ["Rain", "Age", "Ball", "Temperature"],
        correctAnswer: "Rain",
      },
      {
        topicId: "Puzzles",
        question:
          "What belongs to you but other people use it more than you do?",
        answers: ["Your name", "Your time", "Your phone", "Your money"],
        correctAnswer: "Your name",
      },
      {
        topicId: "Puzzles",
        question: "What begins with T, ends with T, and has T in it?",
        answers: ["Teapot", "Tent", "Ticket", "Toilet"],
        correctAnswer: "Teapot",
      },
      {
        topicId: "Puzzles",
        question: "What word is spelled incorrectly in every dictionary?",
        answers: ["Incorrectly", "Wrong", "Misspelled", "None"],
        correctAnswer: "Incorrectly",
      },
      {
        topicId: "Puzzles",
        question: "Forward I am heavy, but backward I am not. What am I?",
        answers: ["Ton", "Stone", "Train", "Elephant"],
        correctAnswer: "Ton",
      },
      {
        topicId: "Puzzles",
        question:
          "If you drop me, I’m sure to crack. But give me a smile, and I’ll always smile back. What am I?",
        answers: ["Mirror", "Egg", "Face", "Glass"],
        correctAnswer: "Mirror",
      },
      {
        topicId: "Puzzles",
        question:
          "What runs, but never walks; has a bed, but never sleeps; has a mouth, but never eats?",
        answers: ["River", "Clock", "Engine", "Storm"],
        correctAnswer: "River",
      },
      {
        topicId: "Puzzles",
        question: "What can you catch, but not throw?",
        answers: ["Cold", "Ball", "Virus", "Breath"],
        correctAnswer: "Cold",
      },
      {
        topicId: "Puzzles",
        question: "What is full of holes but still holds water?",
        answers: ["Sponge", "Net", "Bucket", "Strainer"],
        correctAnswer: "Sponge",
      },
    ],
  ],
];

module.exports = { questionBank };
